import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../../lib/api";
import { getSocket } from "../../lib/socket";
import { Card, EmptyState, LoadingState, PageHeader, Td, Th, formatDate } from "../../components/Shared";
import { RiskChip, StatusPill } from "../../components/RiskChip";

export default function AlertsQueue() {
  const [alerts, setAlerts] = useState<any[]>([]);
  const [status, setStatus] = useState("");
  const [loading, setLoading] = useState(true);

  function load() {
    setLoading(true);
    const params = status ? `?status=${status}` : "";
    api.get<any[]>(`/api/compliance/alerts${params}`).then((a) => {
      setAlerts(a);
      setLoading(false);
    });
  }

  useEffect(load, [status]);

  useEffect(() => {
    let cleanup = () => {};
    getSocket().then((socket) => {
      if (!socket) return;
      const onEvent = () => load();
      socket.on("alert.created", onEvent);
      socket.on("alert.updated", onEvent);
      cleanup = () => {
        socket.off("alert.created", onEvent);
        socket.off("alert.updated", onEvent);
      };
    });
    return () => cleanup();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div>
      <PageHeader title="Alerts" subtitle="Compliance alerts generated by the risk engine." />

      <div className="mb-4 flex gap-3">
        {["", "new", "under_review", "escalated", "resolved", "false_positive", "closed"].map((s) => (
          <button
            key={s}
            onClick={() => setStatus(s)}
            className={`rounded-full px-3 py-1.5 text-xs font-semibold capitalize ${status === s ? "bg-navy-900 text-white" : "bg-slate-100 text-slate-600"}`}
          >
            {s === "" ? "All" : s.replace("_", " ")}
          </button>
        ))}
      </div>

      <Card>
        {loading ? <LoadingState /> : alerts.length === 0 ? (
          <EmptyState message="No alerts." />
        ) : (
          <table className="w-full">
            <thead>
              <tr className="border-b border-slate-100">
                <Th>Created</Th><Th>Rule</Th><Th>Risk</Th><Th>Status</Th><Th>Assigned</Th><Th></Th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {alerts.map((a) => (
                <tr key={a.id}>
                  <Td>{formatDate(a.createdAt)}</Td>
                  <Td>{a.primaryRuleCode}</Td>
                  <Td><RiskChip level={a.riskLevel} /> <span className="text-xs text-slate-400">{a.riskScore}</span></Td>
                  <Td><StatusPill status={a.status} /></Td>
                  <Td className="text-xs">{a.assignedTo ? a.assignedTo.slice(0, 8) : "Unassigned"}</Td>
                  <Td><Link to={`/compliance/alerts/${a.id}`} className="text-xs font-semibold text-teal-700">Investigate</Link></Td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </Card>
    </div>
  );
}
